### ISSUE TITLE
Inspire HD

### ISSUE THREAD

**Issue by YasserAntonio** [cryptax/fittools#2]
Hi ! Any idea if it will work with a Fitbit inspire HR ? 

Thanks

**Comment by cryptax** [comment]
this dates back 5 years ago, I'd be surprised it still works on current devices.

**Comment by YasserAntonio** [comment]
I asked with few hope too. Still I will look for a way
 but I need to learn more about embedded system and C first . I will try to learn based on your work. Thanks for your sharing.
